### ISSUE TITLE
Command Failed: grunt when running with pre-commit hook

### ISSUE THREAD

**Issue by bryantAXS** [wecodemore/grunt-githooks#71]
When I submit a commit, the hook triggers but displays this error:

```
{ Error: Command failed: grunt

    at ChildProcess.exithandler (child_process.js:272:12)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5) killed: false, code: 3, signal: null, cmd: 'grunt' }
```

My config is as follows:

```
githooks: {
      all: {
        'pre-commit': [
          'uglify',
          'cssmin',
          'shell:addfiles'
        ]
      }
    },
```

I have grunt installed locally and globally. Any thoughts? Thank you!

**Comment by franz-josef-kaiser** [comment]
Have you tried removing two of the three commands in your `pre-commit` hook? That would make it easier to track down the faulty part. Please do some more debugging by removing and adding back in things to narrow the range of possible causes. From the error message above, it is impossible to tell where the bug is burried.
